version: "3"

services:
  #######################################
  # Postgres
  #######################################
  db:
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-readflow_test}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-testpwd}

  ########################################
  # API
  ########################################
  api:
    image: "golang:1.17"
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    environment:
      - READFLOW_AUTHN=mock
      - READFLOW_DB=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-testpwd}@db/${POSTGRES_DB:-readflow_test}?sslmode=disable
    ports:
      - "${API_PORT:-8080}:8080"

  ########################################
  # Webapp
  ########################################
  app:
    image: "node:lts-alpine"
    depends_on:
      - api
    volumes:
      - ./ui:/app
    working_dir: /app
    command: npm start
    environment:
      - REACT_APP_API_ROOT=http://localhost:${API_PORT:-8080}
      - REACT_APP_AUTHORITY=mock
    ports:
      - "${APP_PORT:-3000}:3000"
